import AppKit

/// 从 NSPasteboard 读取内容，并遵循 nspasteboard.org 的隐私约定
public enum PasteboardReader {
    /// 本应用写入剪贴板时附带的标记，监听时据此跳过自身写入
    public static let markerType = NSPasteboard.PasteboardType("io.github.no1coder.Cubby.marker")

    /// 密码管理器等应用标记的机密 / 临时 / 自动生成内容，一律不记录
    static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "net.antelle.keeweb",
        markerType.rawValue,
    ]

    public static func shouldIgnore(_ pasteboard: NSPasteboard) -> Bool {
        guard let types = pasteboard.types, !types.isEmpty else { return true }
        return types.contains { ignoredTypes.contains($0.rawValue) }
    }

    /// 监听剪贴板时在主线程调用：只取出数据，不做耗时处理。
    /// 读取优先级：文件 > 文本 > 图片（Finder 复制文件时也会附带文件名文本与图标）。
    /// 只提供 TIFF 的图片返回原始字节（.rawImage），转码为 PNG 留给后台（ClipStore.recordInBackground）
    public static func capture(from pasteboard: NSPasteboard) -> PasteboardCapture? {
        if let files = readFiles(pasteboard) { return .content(files) }
        if let text = readText(pasteboard) { return .content(text) }
        if let png = pasteboard.data(forType: .png) {
            // PNG 超限时不再回退 TIFF：同一张图的 TIFF 更大，转码后必然同样超限，只会白白耗时
            guard png.count <= CaptureLimits.maxImageBytes else { return nil }
            if let content = pngContent(png) { return .content(content) }
        }
        return readRawTIFF(pasteboard).map(PasteboardCapture.rawImage)
    }

    /// 同步读取并规范化（TIFF 当场转为 PNG，大图会耗时上百毫秒）：供不在主线程、或需要直接得到可入库内容的场景使用
    public static func read(from pasteboard: NSPasteboard) -> ClipContent? {
        switch capture(from: pasteboard) {
        case .content(let content): content
        case .rawImage(let raw): try? ImageNormalizer.normalize(raw).content
        case nil: nil
        }
    }

    private static func readFiles(_ pasteboard: NSPasteboard) -> ClipContent? {
        let options: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
        guard let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: options) as? [URL],
            !urls.isEmpty
        else { return nil }
        return .files(urls)
    }

    private static func readText(_ pasteboard: NSPasteboard) -> ClipContent? {
        guard let text = pasteboard.string(forType: .string),
            !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
            text.utf8.count <= CaptureLimits.maxTextBytes
        else { return nil }

        let formats = readRichFormats(pasteboard)
        return formats.isEmpty ? .text(text) : .richText(text, formats: formats)
    }

    /// 读取随文本一起提供的 RTF / HTML 等格式，粘贴时可保留原样式
    private static func readRichFormats(_ pasteboard: NSPasteboard) -> [String: Data] {
        let available = Set(pasteboard.types?.map(\.rawValue) ?? [])
        return RichFormats.supportedTypes.reduce(into: [:]) { result, type in
            guard available.contains(type),
                let data = pasteboard.data(forType: NSPasteboard.PasteboardType(type)),
                !data.isEmpty,
                data.count <= CaptureLimits.maxFormatBytes
            else { return }
            result[type] = data
        }
    }

    /// PNG 直接入库；尺寸取自文件头（NSBitmapImageRep 对 PNG 延迟解码，这里不会解码像素）。无法识别时返回 nil
    private static func pngContent(_ png: Data) -> ClipContent? {
        guard let rep = NSBitmapImageRep(data: png) else { return nil }
        return .image(png: png, width: rep.pixelsWide, height: rep.pixelsHigh)
    }

    /// 截图等场景通常只提供 TIFF：主线程只取字节，并用文件头确认是能识别的图片（不解码像素），
    /// 统一转为体积更小的 PNG 在后台进行
    private static func readRawTIFF(_ pasteboard: NSPasteboard) -> RawImage? {
        guard let tiff = pasteboard.data(forType: .tiff),
            tiff.count <= CaptureLimits.maxTIFFBytes,
            let source = CGImageSourceCreateWithData(tiff as CFData, nil),
            CGImageSourceGetType(source) != nil,
            CGImageSourceGetCount(source) > 0
        else { return nil }
        return RawImage(data: tiff)
    }
}
