import AppKit
import Testing
@testable import CubbyCore

@Suite("PasteboardReader 读取与隐私过滤", .serializedPasteboardAccess, .timeLimit(.minutes(1)))
struct PasteboardReaderTests {
    /// 统一比较真实路径，规避 /var 与 /private/var 的符号链接差异
    private func resolvedPaths(_ urls: [URL]) -> [String] {
        urls.map { $0.resolvingSymlinksInPath().path }
    }

    private func makeFiles(_ names: [String], in dir: URL) throws -> [URL] {
        try names.map { name in
            let url = dir.appendingPathComponent(name)
            try Data(name.utf8).write(to: url)
            return url
        }
    }

    // MARK: - shouldIgnore

    @Test("空剪贴板应忽略且读取为 nil")
    func emptyPasteboard() {
        withTemporaryPasteboard { pasteboard in
            #expect(PasteboardReader.shouldIgnore(pasteboard))
            #expect(PasteboardReader.read(from: pasteboard) == nil)
        }
    }

    @Test("普通文本不应忽略")
    func plainTextIsNotIgnored() {
        withTemporaryPasteboard { pasteboard in
            pasteboard.setString("hello", forType: .string)
            #expect(!PasteboardReader.shouldIgnore(pasteboard))
        }
    }

    @Test(
        "带隐私标记类型的内容应忽略",
        arguments: [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
            "com.agilebits.onepassword",
            "de.petermaurer.TransientPasteboardType",
            "com.typeit4me.clipping",
            "Pasteboard generator type",
            "net.antelle.keeweb",
            PasteboardReader.markerType.rawValue,
        ])
    func markedContentIsIgnored(_ type: String) {
        withTemporaryPasteboard { pasteboard in
            pasteboard.setString("secret-password", forType: .string)
            pasteboard.setData(Data(), forType: NSPasteboard.PasteboardType(type))
            #expect(PasteboardReader.shouldIgnore(pasteboard))
        }
    }

    // MARK: - 文本

    @Test("读取文本")
    func readsText() {
        withTemporaryPasteboard { pasteboard in
            pasteboard.setString("你好 📋\n第二行", forType: .string)
            #expect(PasteboardReader.read(from: pasteboard) == .text("你好 📋\n第二行"))
        }
    }

    @Test("URL 形式的文本仍按文本读取", arguments: ["https://example.com", "/tmp/not-a-file-url"])
    func urlLikeStringIsText(_ value: String) {
        withTemporaryPasteboard { pasteboard in
            pasteboard.setString(value, forType: .string)
            #expect(PasteboardReader.read(from: pasteboard) == .text(value))
        }
    }

    @Test("空白文本被忽略", arguments: ["", "   ", "\n\t \n"])
    func blankTextIsIgnored(_ value: String) {
        withTemporaryPasteboard { pasteboard in
            pasteboard.setString(value, forType: .string)
            #expect(PasteboardReader.read(from: pasteboard) == nil)
        }
    }

    @Test("超过大小上限的文本被忽略，恰好等于上限时保留")
    func oversizedTextIsIgnored() {
        withTemporaryPasteboard { pasteboard in
            let exact = String(repeating: "a", count: CaptureLimits.maxTextBytes)
            pasteboard.setString(exact, forType: .string)
            #expect(PasteboardReader.read(from: pasteboard) == .text(exact))

            pasteboard.clearContents()
            pasteboard.setString(exact + "a", forType: .string)
            #expect(PasteboardReader.read(from: pasteboard) == nil)
        }
    }

    // MARK: - 文件

    @Test("读取文件 URL（真实文件）")
    func readsFileURLs() throws {
        let dir = try TempDirectory.make()
        defer { TempDirectory.remove(dir) }
        let urls = try makeFiles(["a.txt", "b c.txt"], in: dir)

        withTemporaryPasteboard { pasteboard in
            pasteboard.writeObjects(urls.map { $0 as NSURL })
            guard case .files(let read) = PasteboardReader.read(from: pasteboard) else {
                Issue.record("应读取为文件")
                return
            }
            #expect(resolvedPaths(read) == resolvedPaths(urls))
            #expect(!PasteboardReader.shouldIgnore(pasteboard))
        }
    }

    @Test("同时存在文件与文本时优先读取文件")
    func filesTakePriorityOverText() throws {
        let dir = try TempDirectory.make()
        defer { TempDirectory.remove(dir) }
        let file = try makeFiles(["doc.txt"], in: dir)[0]

        withTemporaryPasteboard { pasteboard in
            let item = NSPasteboardItem()
            item.setString(file.absoluteString, forType: .fileURL)
            item.setString("doc.txt", forType: .string)
            item.setData(ImageFixtures.png(width: 2, height: 2), forType: .png)
            pasteboard.writeObjects([item])

            guard case .files(let read) = PasteboardReader.read(from: pasteboard) else {
                Issue.record("应优先读取为文件")
                return
            }
            #expect(resolvedPaths(read) == resolvedPaths([file]))
        }
    }

    @Test("普通网页 URL 不会被当作文件")
    func webURLIsNotFile() {
        withTemporaryPasteboard { pasteboard in
            pasteboard.writeObjects([URL(string: "https://example.com/a")! as NSURL])
            let content = PasteboardReader.read(from: pasteboard)
            if case .files = content {
                Issue.record("网页 URL 不应读取为文件：\(String(describing: content))")
            }
        }
    }

    // MARK: - 图片

    @Test("读取 PNG，保留原始数据与尺寸")
    func readsPNG() {
        withTemporaryPasteboard { pasteboard in
            let png = ImageFixtures.png(width: 4, height: 3)
            pasteboard.setData(png, forType: .png)
            #expect(PasteboardReader.read(from: pasteboard) == .image(png: png, width: 4, height: 3))
        }
    }

    @Test("仅有 TIFF 时转换为 PNG")
    func convertsTIFFToPNG() {
        withTemporaryPasteboard { pasteboard in
            pasteboard.setData(ImageFixtures.tiff(width: 5, height: 7), forType: .tiff)
            guard case .image(let png, let width, let height) = PasteboardReader.read(from: pasteboard) else {
                Issue.record("应读取为图片")
                return
            }
            #expect(ImageFixtures.isPNG(png))
            #expect(width == 5 && height == 7)
            #expect(NSBitmapImageRep(data: png)?.pixelsWide == 5)
        }
    }

    @Test("PNG 数据无法解码时回退到 TIFF")
    func invalidPNGFallsBackToTIFF() {
        withTemporaryPasteboard { pasteboard in
            let item = NSPasteboardItem()
            item.setData(Data("not a png".utf8), forType: .png)
            item.setData(ImageFixtures.tiff(width: 2, height: 2), forType: .tiff)
            pasteboard.writeObjects([item])

            guard case .image(let png, 2, 2) = PasteboardReader.read(from: pasteboard) else {
                Issue.record("应回退读取 TIFF")
                return
            }
            #expect(ImageFixtures.isPNG(png))
        }
    }

    @Test("无法解码的图片数据返回 nil")
    func undecodableImageReturnsNil() {
        withTemporaryPasteboard { pasteboard in
            pasteboard.setData(Data("garbage".utf8), forType: .png)
            #expect(PasteboardReader.read(from: pasteboard) == nil)
        }
    }

    @Test("同时有文本与图片时优先文本")
    func textTakesPriorityOverImage() {
        withTemporaryPasteboard { pasteboard in
            let item = NSPasteboardItem()
            item.setString("caption", forType: .string)
            item.setData(ImageFixtures.png(width: 2, height: 2), forType: .png)
            pasteboard.writeObjects([item])
            #expect(PasteboardReader.read(from: pasteboard) == .text("caption"))
        }
    }
}
